about/urls.py
from django.urls import path

from . import views

app_name = "index"
urlpatterns = [
path('', views.index, name="index"),
]

#path('about/', views.about, name="about")

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    
]

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'about/index.html')

#def about(request):
#    return render(request,'about/about.html')

templates/about/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <!-- Personal CSS file -->
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
</head>

<div class="container" style="max-width: 42em;">
    <main role="main" class="inner cover">
        <!--Profile Picture-->
        <div class="text-center">
            <img class="bd-img bd-img-lg featurette-image img-fluid mx-auto rounded-circle"
                src="{% static 'img/appuinus.JPG' %}" width="300" height="300" focusable="false" role="img"
                aria-label="appu">
            <title>1ntrud3r</title>
            <rect width="100%" height="100%" fill="#eee" /></img>
        </div>
        <!--//Profile Picture "DSC_0002_Original.jpg"-->
        <h1 class="cover-heading">Appu Raj V</h1>
        <p class="lead text" style="color: rgba(255, 255, 255, .5);">Security Ninja, who one day will break into systems
        </p>
        <p class="lead">The secret ingredient is... nothing ! To make something special you just have to believe it's
            special.</p>
        <p class="lead">
            <!--//Get In Touch-->
            <a class="nav-item btn btn-primary font-weight-bold" href="mailto:appurajv@icloud.com"
                style="background-color: white; border: 0; color: #1b1b1d;">Contact</a>
            <a class="nav-item btn btn-primary font-weight-bold"
                href="{% static 'pdf/Appu_resume_final2.pdf' %}"
                style="background-color: white; border: 0; color: #1b1b1d;" target="_blank"
                type=application/pdf>Resume</a>
            <!--//Get In Touch-->
            <!--Social Proof Buttons-->
            <div class="container my-2">
                <a class="nav-item fab fa-github-square fa-2x" style="color: white; background-color: #1b1b1d;"
                    href="https://github.com/appurajv" target="_blank"></a>
                <a class="nav-item fab fa-linkedin fa-2x" href="https://www.linkedin.com/in/appu-raj/"
                    target="_blank"></a>
            </div>
            <!--//Social Proof Buttons-->
        </p>
    </main>
</div>

{% endblock %}

templates/about/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <!-- Personal CSS file -->
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
</head>

<div class="container" style="max-width: 42em;">
    <main role="main" class="inner cover">
        <!--Profile Picture-->
        <div class="text-center">
            <img class="bd-img bd-img-lg featurette-image img-fluid mx-auto rounded-circle"
                src="{% static 'img/appuinus.JPG' %}" width="300" height="300" focusable="false" role="img"
                aria-label="appu">
            <title>1ntrud3r</title>
            <rect width="100%" height="100%" fill="#eee" /></img>
        </div>
        <!--//Profile Picture "DSC_0002_Original.jpg"-->
        <h1 class="cover-heading">Appu Raj V</h1>
        <p class="lead text" style="color: rgba(255, 255, 255, .5);">Security Ninja, who one day will break into systems
        </p>
        <p class="lead">The secret ingredient is... nothing ! To make something special you just have to believe it's
            special.</p>
        <p class="lead">
            <!--//Get In Touch-->
            <a class="nav-item btn btn-primary font-weight-bold" href="mailto:appurajv@icloud.com"
                style="background-color: white; border: 0; color: #1b1b1d;">Contact</a>
            <a class="nav-item btn btn-primary font-weight-bold"
                href="{% static 'pdf/Appu_resume_final2.pdf' %}"
                style="background-color: white; border: 0; color: #1b1b1d;" target="_blank"
                type=application/pdf>Resume</a>
            <!--//Get In Touch-->
            <!--Social Proof Buttons-->
            <div class="container my-2">
                <a class="nav-item fab fa-github-square fa-2x" style="color: white; background-color: #1b1b1d;"
                    href="https://github.com/appurajv" target="_blank"></a>
                <a class="nav-item fab fa-linkedin fa-2x" href="https://www.linkedin.com/in/appu-raj/"
                    target="_blank"></a>
            </div>
            <!--//Social Proof Buttons-->
        </p>
    </main>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>1ntrud3r</title>

    <!-- Bootstrap CSS: 4.5.3 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Personal CSS file -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!--Font Awesome 5-->
    <script src="https://kit.fontawesome.com/94b5d0018e.js" crossorigin="anonymous"></script>
    <!--//Font Awesome 5-->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Navbar-->

<body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="container" style="max-width: 40em;">
                <h3 class="masthead-brand">Portfolio</h3>
                <nav class="nav nav-masthead justify-content-center testing" id="nav-bar">
                    <a class="nav-link" href="{% url 'index:index' %}">Home</a>

                </nav>
            </div>
        </header>

        </head>

        <hr class="divider">

        <body>

            <div class="container">
                {% block content %}

                {% endblock %}
            </div>

            <hr class="divider">

            <footer class="mastfoot mt-auto">
                <div class="inner">
                    <p>Designed & Built by <a href="https://github.com/appurajv/appu-website"
                            target="_blank">Appu</a></p>
                </div>
            </footer>

            <!-- jQuery and Bootstrap Bundle (includes Popper) -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
                crossorigin="anonymous"></script>

            <!-- Custom JS -->

            <!-- Navigation buttons have active state when coinciding page is loaded -->
            <script type="text/javascript">
                var loc = window.location.pathname;

                $('.testing').find('a').each(function () {
                    $(this).toggleClass('active', $(this).attr('href') == loc);
                });
            </script>

        </body>

</html>